version: 2.1
orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.0.2
jobs:
  coverage:
    steps:
      - codecov/upload:
          file: {{ coverage_report_filepath }}
workflows:
  build_and_test:
    jobs:
      - node/test
      - coverage